# Generated by Django 3.1.5 on 2021-02-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_auto_20210215_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['value']},
        ),
        migrations.AddField(
            model_name='bid',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('value', 'order')},
        ),
    ]
