# Generated by Django 3.1.5 on 2021-02-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0013_auto_20210217_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='placer',
        ),
    ]
